In [1]:
import tensorflow as tf

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 1. Visualize it with TensorBoard
运行程序后执行：<br>
- tensorboard --logdir=C:/Users/Administrator/CS20SI/graphs <br>
- http://localhost:6006/

In [2]:
a = tf.constant (2)
b = tf.constant (3)
c = tf.add (a, b)

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print (sess.run (c))
writer.close()

5


## 2 constant 
tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const',
    verify_shape=False
) <br>
function ： 创建一个constant张量，值不可改变 <br>
**constant较为简单，没有太多的内容**

In [3]:
a_1 = tf.constant (1, name = 'a_1')
# 维度后续部分全部更新为2
b_1 = tf.constant ([1, 2], shape = (2, 3), name = 'b_1')
c_1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'c_1')
result_1 = tf.add (a_1, b_1)

with tf.Session() as sess:
    print (sess.run (a_1))
    print (sess.run (b_1))
    print (sess.run (c_1))
    print (sess.run (result_1))

1
[[1 2 2]
 [2 2 2]]
[[1 2 3]
 [4 5 6]]
[[2 3 3]
 [3 3 3]]


#### 2.1 Tensors filled with a specific value
一些特殊的constant函数 <br>
tf.zeros(shape, dtype=tf.float32, name=None)<br>
tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)<br>
tf.ones(shape, dtype=tf.float32, name=None)<br>
tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)<br>
tf.fill(dims, value, name=None)  # 填充value元素

In [4]:
a_2 = tf.zeros([2, 2])
b_2 = tf.zeros_like (b_1)
c_2 = tf.fill ([3, 1], 8)
with tf.Session() as sess:
    print (sess.run(a_2))
    print (sess.run(b_2))
    print (sess.run (c_2))

[[0. 0.]
 [0. 0.]]
[[0 0 0]
 [0 0 0]]
[[8]
 [8]
 [8]]


#### 2.2 Constants as sequences
序列取constant值： <br>
tf.linspace(start, stop, num, name=None) <br>
tf.range(start, limit=None, delta=1, dtype=None, name='range')

In [5]:
a_3 = tf.linspace(10.0, 20.0, 5)
b_3 = tf.range (1, 5, 3)
c_3 = tf.range (10)
with tf.Session() as sess:
    print (sess.run (a_3))
    print (sess.run (b_3))
    print (sess.run (c_3))

[10.  12.5 15.  17.5 20. ]
[1 4]
[0 1 2 3 4 5 6 7 8 9]


#### 2.3 Randomly Generated Constants
随机取值 <br>
tf.random_normal <br>
tf.truncated_normal <br>
tf.random_uniform <br>
tf.random_shuffle <br>
tf.random_crop <br>
tf.multinomial <br>
tf.random_gamma <br>


#### 2.4 Arithmetic Ops


In [6]:
a = tf.constant([3, 6])
b = tf.constant([2, 2])

with tf.Session() as sess:
    print (tf.add(a, b).eval())
    # 连加
    print (tf.add_n([a, b, b]).eval())
    print (tf.multiply (a, b).eval())
    # 矩阵相乘
    # tf.matmul (a, b) 会报错
    print (tf.matmul (tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1])).eval())
    # 商
    print (tf.div (a, b).eval())
    # 余
    print (tf.mod (a, b).eval())

[5 8]
[ 7 10]
[ 6 12]
[[18]]
[1 3]
[1 0]
